### ISSUE TITLE
void de.myDom.Service.writePerson(Person) executed in 4ms

### ISSUE THREAD

**Issue by kldm1011** [kldm1011/annotProj#1]
https://sentry.io/esentry/dmitrij_project/issues/491673869/

```
Stacktrace (aktuellster Aufruf als erstes):

    at de.myDom.aspect.ExampleAspect.logExecutionTime(ExampleAspect.java:31)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
    at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)

void de.myDom.Service.writePerson(Person) executed in 4ms
```

**Comment by kldm1011** [comment]
closed
